export const technicalQuestions = [
  "Explain closure in JavaScript.",
  "What is React Virtual DOM?",
  "Difference between var, let, and const?",
  "Explain async/await in JS.",
  "What is REST API?",
  "What is useEffect?",
  "Explain event loop.",
  "What is state in React?",
  "Difference between SQL and NoSQL?",
  "What is hoisting?",
  "Explain promises.",
  "What is JWT?",
  "What is middleware?",
  "Explain CSS Flexbox.",
  "What is responsive design?",
];

export const hrQuestions = [
  "Tell me about yourself.",
  "Why should we hire you?",
  "What are your strengths?",
  "What are your weaknesses?",
  "Describe a challenge you faced.",
  "Where do you see yourself in 5 years?",
  "Why do you want this role?",
  "How do you handle pressure?",
  "Describe teamwork experience.",
  "What motivates you?",
  "Why should we select you?",
  "Tell me about a failure.",
  "Are you open to relocation?",
  "Describe leadership experience.",
  "What are your career goals?",
];
